{
 "title": "couchDB Nodes Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Select couchDB Instance",
    "query": {
     "query": "label_values($instance{$instance=\"$instance\"},instance)"
    }
   },
   { "name": "db_name", "query": { "query": "couchdb_database_info" } }
  ]
 },
 "panels": [
  {
   "title": "Erlang Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "couchdb_erlang_memory_atom_used{instance=\"$instance\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Open OS files",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "couchdb_httpd_open_os_files{instance=\"$instance\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Open Databases",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "couchdb_httpd_open_databases{instance=\"$instance\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Database Writes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "couchdb_httpd_database_writes{instance=\"$instance\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Database Reads",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "couchdb_httpd_database_reads{instance=\"$instance\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "View Reads",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "couchdb_httpd_view_reads{instance=\"$instance\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Temporary View Reads",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "couchdb_httpd_temporary_view_reads{instance=\"$instance\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Bulk Requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "couchdb_httpd_bulk_requests{instance=\"$instance\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "couchdb_httpd_request_time{instance=\"$instance\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Request Methods",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "couchdb_httpd_request_methods{instance=\"$instance\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Response Status  Overview",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "couchdb_httpd_status_codes{instance=\"$instance\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Log Types",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "targets": [
    { "expr": "couchdb_server_couch_log", "legendFormat": "{{node_name}}-{{level}}" }
   ]
  },
  {
   "title": "System Logs",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "couchdb_server_couch_log", "legendFormat": "{{node_name}}-{{level}}" }
   ]
  }
 ]
}