{
 "title": "couchDB Overview Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Select couchDB Instance",
    "query": {
     "query": "label_values($instance{$instance=\"$instance\"},instance)"
    }
   },
   { "name": "db_name", "query": { "query": "couchdb_database_info" } }
  ]
 },
 "panels": [
  {
   "title": "Number of Clusters",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(couchdb_replicator_cluster_is_stable{instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(couchdb_httpd_node_up{instance=\"$instance\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Clusters Healthy",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(couchdb_replicator_cluster_is_stable{instance=\"$instance\"})*100/sum(couchdb_replicator_cluster_is_stable{instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Database Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "couchdb_database_data_size{db_name=\"$db_name\"}",
     "legendFormat": "{{db_name}}"
    }
   ]
  },
  {
   "title": "Database Document Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(couchdb_database_doc_count{db_name=\"$db_name\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Database Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(couchdb_httpd_databases_total[5m])",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Database Writes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg(couchdb_httpd_database_writes{instance=\"$instance\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Open OS files",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "avg(couchdb_httpd_open_os_files{instance=\"$instance\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "View Reads",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg(couchdb_httpd_view_reads{instance=\"$instance\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Open Databases",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "avg(couchdb_httpd_open_databases{instance=\"$instance\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Database Reads",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg(couchdb_httpd_database_reads{instance=\"$instance\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Temporary View Reads",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg(couchdb_httpd_temporary_view_reads{instance=\"$instance\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Bulk Requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg(couchdb_httpd_bulk_requests{instance=\"$instance\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(node_name, instance) (couchdb_httpd_request_time{instance=\"$instance\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Request Methods",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(node_name, instance) (couchdb_httpd_request_methods{instance=\"$instance\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Response Status  Overview",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(node_name, instance) (couchdb_httpd_status_codes{instance=\"$instance\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Response Statuses",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(node_name, instance) (couchdb_httpd_status_codes{instance=\"$instance\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Clients Requesting Changes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "avg(couchdb_httpd_clients_requesting_changes{instance=\"$instance\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  { "title": "Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Replicator changes manager deaths",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "avg(couchdb_replicator_changes_manager_deaths{instance=\"$instance\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Replicator changes queue deaths",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 38 },
   "targets": [
    {
     "expr": "avg(couchdb_replicator_changes_queue_deaths{instance=\"$instance\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Replicator changes queue deaths",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 38 },
   "targets": [
    {
     "expr": "avg(couchdb_replicator_changes_reader_deaths{instance=\"$instance\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Replicator Failed Starts",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "avg(couchdb_replicator_failed_starts{instance=\"$instance\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Replicator Failed Starts",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "avg(couchdb_replicator_failed_starts{instance=\"$instance\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Replicator Cluster Stability",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "avg(couchdb_replicator_cluster_is_stable{instance=\"$instance\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Replicator Connections",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "avg(couchdb_replicator_connections{instance=\"$instance\"})",
     "legendFormat": "{{node_name}}"
    }
   ]
  }
 ]
}